### ISSUE TITLE
Info About...

### ISSUE THREAD

**Issue by Odi-3** [elementary/fileroller#24] opened 2023-02-02 11:30 UTC
### What Happened?

In some GNOME applications there is an "Info about..." button in the main application menu. In Web, however, it is no longer present. So what is the correct choice?

### Steps to Reproduce

1. Open a GNOME application
2. Open the main application menu

### Expected Behavior

Make one choice for all GNOME applications

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment] 2023-03-27 01:29
Since this is a duplicate of an issue about GNOME Web, closing. We don't make any patches about that here

**Closed by danirabbit** 2023-03-27 01:29 UTC
