### ISSUE TITLE
You cannot select a different viewer program from the compressed file.

### ISSUE THREAD

**Issue by 3N37** [elementary/fileroller#23] opened 2022-12-19 10:15 UTC
### What Happened?

In jolnir, I have these problems:

when trying to preview a compressed file of a tar.gz archive , it is not possible to do Open with ,as the choice remains prefixed on a particular program .

### Steps to Reproduce

[Screen record from 2022-12-19 11.06.59.webm](https://user-images.githubusercontent.com/49634356/208401132-31d9d024-1355-417a-88fa-0f08d9ce68c9.webm)

### Expected Behavior

you should be able to select a different program to visulaize the file

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell

```

### Hardware Info

![immagine](https://user-images.githubusercontent.com/49634356/208401921-a54b62b0-2290-4bf8-bd0b-57c9f414f3ef.png)

**Comment by ryonakano** [comment] 2023-04-01 04:13
Thank you for your reporting.

This issue is a duplicate of https://github.com/elementary/portals/issues/52 and fixed in https://github.com/elementary/portals/pull/53. It should work on the latest elementary OS 7.

**Closed by ryonakano** 2023-04-01 04:13 UTC
